"""统一 Prompt 导出层

非工程人员：所有内容在同目录 markdown 文件中，可直接编辑。
工程兼容：保持原有常量名导出，内部通过 loader 读取。

新增 / 修改 Prompt 步骤：
1. 在 system/ tasks/ 或 checklists_md/ 下新增 .md 文件（首段 YAML 写 id）
2. 在 registry.py 登记 id → 路径
3. 代码中即可 `from prompts import YOUR_PROMPT_ID`

注意：占位符 {variable} 需由调用方 format 提供。
"""

from .loader import get_prompt, safe_format, list_prompts, get_prompt_meta

# 显式常量加载（静态工具可识别这些名称）
SYSTEM_BASE_PROMPT = get_prompt("SYSTEM_BASE_PROMPT")
COORDINATOR_SYSTEM_PROMPT = get_prompt("COORDINATOR_SYSTEM_PROMPT")
PULMONARY_SYSTEM_PROMPT = get_prompt("PULMONARY_SYSTEM_PROMPT")
IMAGING_SYSTEM_PROMPT = get_prompt("IMAGING_SYSTEM_PROMPT")
PATHOLOGY_SYSTEM_PROMPT = get_prompt("PATHOLOGY_SYSTEM_PROMPT")
RHEUMATOLOGY_SYSTEM_PROMPT = get_prompt("RHEUMATOLOGY_SYSTEM_PROMPT")
DATA_ANALYSIS_SYSTEM_PROMPT = get_prompt("DATA_ANALYSIS_SYSTEM_PROMPT")

COORDINATOR_PROMPT = get_prompt("COORDINATOR_PROMPT")
CASE_SUMMARY_PROMPT = get_prompt("CASE_SUMMARY_PROMPT")
RAG_QUERY_PROMPT = get_prompt("RAG_QUERY_PROMPT")

# Coordinator task extensions
COORDINATION_ANALYSIS_PROMPT = get_prompt("COORDINATION_ANALYSIS_PROMPT")
CONFLICT_DETECTION_PROMPT = get_prompt("CONFLICT_DETECTION_PROMPT")
CONSENSUS_EVALUATION_PROMPT = get_prompt("CONSENSUS_EVALUATION_PROMPT")
FINAL_COORDINATION_PROMPT = get_prompt("FINAL_COORDINATION_PROMPT")
PULMONARY_ANALYSIS_PROMPT = get_prompt("PULMONARY_ANALYSIS_PROMPT")
IMAGING_ANALYSIS_PROMPT = get_prompt("IMAGING_ANALYSIS_PROMPT")
PATHOLOGY_ANALYSIS_PROMPT = get_prompt("PATHOLOGY_ANALYSIS_PROMPT")
RHEUMATOLOGY_CTD_ILD_PROMPT = get_prompt("RHEUMATOLOGY_CTD_ILD_PROMPT")
DATA_ANALYSIS_MAIN_PROMPT = get_prompt("DATA_ANALYSIS_MAIN_PROMPT")

PULMONARY_ANALYSIS_CHECKLIST = get_prompt("PULMONARY_ANALYSIS_CHECKLIST")
IMAGING_ANALYSIS_CHECKLIST = get_prompt("IMAGING_ANALYSIS_CHECKLIST")
PATHOLOGY_ANALYSIS_CHECKLIST = get_prompt("PATHOLOGY_ANALYSIS_CHECKLIST")
CTD_ILD_ANALYSIS_CHECKLIST = get_prompt("CTD_ILD_ANALYSIS_CHECKLIST")
DATA_ANALYSIS_CHECKLIST = get_prompt("DATA_ANALYSIS_CHECKLIST")

def reload_all_prompts() -> None:
	"""强制刷新全部已登记提示词缓存（用于 UI 热加载）。"""
	from .registry import PROMPT_FILES
	for _pid in PROMPT_FILES.keys():
		# 直接覆写模块级常量（便于运行中查看最新内容）
		globals()[_pid] = get_prompt(_pid, reload=True)


# 明确导出符号（静态工具可解析）
__all__ = [
	"SYSTEM_BASE_PROMPT",
	"COORDINATOR_SYSTEM_PROMPT",
	"PULMONARY_SYSTEM_PROMPT",
	"IMAGING_SYSTEM_PROMPT",
	"PATHOLOGY_SYSTEM_PROMPT",
	"RHEUMATOLOGY_SYSTEM_PROMPT",
	"DATA_ANALYSIS_SYSTEM_PROMPT",
	"COORDINATOR_PROMPT",
	"CASE_SUMMARY_PROMPT",
	"RAG_QUERY_PROMPT",
	"COORDINATION_ANALYSIS_PROMPT",
	"CONFLICT_DETECTION_PROMPT",
	"CONSENSUS_EVALUATION_PROMPT",
	"FINAL_COORDINATION_PROMPT",
	"PULMONARY_ANALYSIS_PROMPT",
	"IMAGING_ANALYSIS_PROMPT",
	"PATHOLOGY_ANALYSIS_PROMPT",
	"RHEUMATOLOGY_CTD_ILD_PROMPT",
	"DATA_ANALYSIS_MAIN_PROMPT",
	"PULMONARY_ANALYSIS_CHECKLIST",
	"IMAGING_ANALYSIS_CHECKLIST",
	"PATHOLOGY_ANALYSIS_CHECKLIST",
	"CTD_ILD_ANALYSIS_CHECKLIST",
	"DATA_ANALYSIS_CHECKLIST",
	"get_prompt",
	"list_prompts",
	"get_prompt_meta",
	"safe_format",
	"reload_all_prompts",
]
